spring.application.name=db-refresh-batch

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Batch Configuration
spring.batch.jdbc.initialize-schema=always

# general db configurations
spring.datasource.jdbc-url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#uncomment the below line if you want to initialize the schema on application startup
#spring.sql.init.mode=always

# Primary DataSource (Source Database - PROD)
source.datasource.jdbc-url=${SOURCE_DATASOURCE_URL}
source.datasource.username=root
source.datasource.password=
source.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Secondary DataSource (Target Database - LOWER ENV)
# This will be configured via @Configuration class
target.datasource.jdbc-url=${TARGET_DATASOURCE_URL}
target.datasource.username=root
target.datasource.password=
target.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_FROM}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Batch Job Configuration
batch.job.notification.email=${MAIL_TO}
batch.job.notification.enabled=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework.batch=DEBUG

